name = "grow-up-everyday-explain"
main = "src/index.ts"
compatibility_date = "2026-10-01"

[vars]
ALLOWED_ORIGINS = "https://subeen2.github.io,http://localhost:5173"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "84be39cc8c1e4df2bd7324286c29ab22"

# `npx wrangler vectorize create en-words --dimensions=1536 --metric=cosine`로 먼저 생성
[[vectorize]]
binding = "EN_WORDS"
index_name = "en-words"
